### ISSUE TITLE
Angular not working

### ISSUE THREAD

**Issue by kmliebe** [kmliebe/git-test2#1]
branch "week1" 
https://www.coursera.org/learn/angular/supplement/cgFr3/exercise-instructions-getting-started-with-angular

**Comment by kmliebe** [comment]
![image](https://user-images.githubusercontent.com/62724254/108013942-ca266680-6fda-11eb-9624-ad7171362a98.png)

**Comment by kmliebe** [comment]
![image](https://user-images.githubusercontent.com/62724254/108014628-4a010080-6fdc-11eb-9ebe-6f3e6bfcf24d.png)

**Comment by eppsilon7** [comment]
Here’s a comment with a potential solution. Basically you need to reinstall Angular. https://github.com/angular/angular-cli/issues/11084#issuecomment-417553204

**Comment by kmliebe** [comment]
yeah, I tried that earlier

![image](https://user-images.githubusercontent.com/62724254/108015816-170c3c00-6fdf-11eb-9b3f-77807c6933ed.png)

**Comment by eppsilon7** [comment]
Hmm, looks like con fusion has a dependency conflict with type script. Wonder if you have to create an older Angular project. Unfortunately I don’t have access to your course instructions so I can’t tell for sure. I can take a closer look tomorrow if you don’t have it working by then.

**Comment by LonnyGomes** [comment]
an Angular upgrade may be in order:
https://update.angular.io/?v=6.1-11.0

That or you downgrade node (which is less than ideal)
